version: "3.8"
services:
  chatbot:
    build: .
    container_name: chatbot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - .wwebjs_auth:/app/.wwebjs_auth
    platform: linux/amd64
